name: "Continuous Integration"
on: 
  push: 
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

permissions: 
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hi"