name: "Continuous Integration"

on: 
  pull_request:
  push:
    branches:
      - main 
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
 
permissions: 
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v6
     - uses: actions/setup-python@v6 
       with:
        python-version-file: .python-version
     - name: pip install
       run: |
        pip install --upgrade pip
        pip install --requirement requirements.txt

     - name: pytest
       run: pytest .
