name: "Continuous Integration"
on: 
  push: 
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

permissions: 
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v6
     - uses: actions/setup-python@v6 
       with:
        python-version-file: .python-version
     - name: pip install
       run: |
        pip install --upgrade pip
        pip install --requirement requirements.txt

     - name: pytest
       run: pytest .
